### ISSUE TITLE
[Errno 13] error while attempting to bind on address ('0.0.0.0', 80): permission denied

### ISSUE THREAD

**Issue by akuma-your-death** [ScRiPt1337/Teardroidv4_api#10]
if i run uvicorn main:app --host 0.0.0.0 --port 80:
INFO:     Started server process [338]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
ERROR:    [Errno 13] error while attempting to bind on address ('0.0.0.0', 80): permission denied
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.

with sudo:
ModuleNotFoundError: No module named 'fastapi' 

but i already installed fastapi

**Comment by ScRiPt1337** [comment]
please run the command as root and make sure all python deps also installed as root
